#!/usr/bin/env python3

import qrcode
import sys
import os

def generate(qr_data, output_file):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(qr_data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")
    img.save(output_file)

if __name__ == "__main__":
    generate(sys.argv[1], os.path.join('/output', sys.argv[2]))