#!/usr/bin/env python3

import qrcode
import sys
import os

def generate_wifi_qr(ssid, password, output_file, security='WPA'):
    wifi_data = f"WIFI:T:{security};S:{ssid};P:{password};;"
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(wifi_data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")
    img.save(output_file)

if __name__ == "__main__":
    if len(sys.argv) != 5:
        print("Usage: qr <SSID> <PASSWORD> <OUTPUT_FILE> <SECURITY>")
        sys.exit(1)
    ssid = sys.argv[1]
    password = sys.argv[2]
    output_file = os.path.join('./', sys.argv[3])
    security = sys.argv[4] if len(sys.argv) > 4 else 'WPA'
    generate_wifi_qr(ssid, password, output_file, security)